name: agro_plaga_ai
description: Aplicación móvil AgroPlaga — detección de plagas en invernadero
publish_to: "none"
version: 2.0.0+4

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: 1.6.0
  flutter_dotenv: ^6.0.1
  flutter_map: ^8.3.0
  shared_preferences: ^2.0.0
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.1.2
  image: ^4.5.4
  tflite_flutter: ^0.12.1
  fl_chart: ^0.70.2
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/branding/app_logo.png
    - assets/ml/labels.txt
    - assets/ml/plaga_model.tflite
